name: Build

on:
  push:
    branches: [ main ]
    tags: [ '*.*.*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.cache/coursier/v1
            ~/.ivy2/cache
          key: ${{ runner.os }}-build-cache-${{ hashFiles('*.sbt') }}-${{ hashFiles('project/*') }}
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: zulu@1.8
      - run: sbt scalafmtCheckAll scalafmtSbtCheck scripted publishLocal
      - uses: actions/upload-artifact@v2
        with:
          name: intellij-unison
          path: /home/runner/.ivy2/local
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: "true"